spring:
  application:
    name: TaskBoard

  datasource:
    url: jdbc:postgresql://localhost:5432/taskboard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true